[package]
name = "anilang"
version = "0.1.0"
authors = ["Lutetium-Vanadium <luv.s7000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.17.7"
app_dirs2 = "2.3"
anilang-core = { path="core" }
