[package]
name = "lexer"
version = "0.1.0"
authors = ["Lutetium Vanadium"]
edition = "2018"

[dependencies]
diagnostics = { path = "../diagnostics" }
source = { path = "../source" }
intermediaries = { path = "../intermediaries" }
